abstract class FormValidator {
  String name();
  String required(String filed);
  String minLength(String filed, String v, int n);
  String maxLength(String filed, String v, int n);
  String email(String filed, String v);
  String phoneNumber(String filed, String v);
  String ip(String filed, String v);
  String ipv6(String filed, String v);
  String url(String filed, String v);
  String fqdn(String filed, String v);
  String alpha(String filed, String v);
  String numeric(String filed, String v);
  String alphanumeric(String filed, String v);
  String base64(String filed, String v);
  String isInt(String filed, String v);
  String isFloat(String filed, String v);
  String hexadecimal(String filed, String v);
  String hexColor(String filed, String v);
  String lowercase(String filed, String v);
  String uppercase(String filed, String v);
  String divisibleBy(String filed, String v, int n);
  String isNull(String filed, String v);
  String length(String filed, String v, int n);
  String byteLength(String filed, String v, int n);
  String uuid(String filed, String v);
  String date(String filed, String v);
  String after(String filed, String v, [DateTime? date]);
  String before(String filed, String v, [DateTime? date]);
  String creditCard(String filed, String v);
  String isbn(String filed, String v);
  String json(String filed, String v);
  String multibyte(String filed, String v);
  String ascii(String filed, String v);
  String fullWidth(String filed, String v);
  String halfWidth(String filed, String v);
  String variableWidth(String filed, String v);
  String surrogatePair(String filed, String v);
  String mongoId(String filed, String v);
  String postalCode(String filed, String v);
  String between(String filed, String v, double min, double max);
  String maxValue(String filed, String v, double max);
  String minValue(String filed, String v, double min);
  String isAfterOrEqualDate(String filed, String v, DateTime afterDate);
  String isBeforeOrEqualDate(String filed, String v, DateTime beforeDate);
  String isNotEqualDate(String filed, String v, DateTime equalDate);
  String isNotEqualDay(String filed, String v, int day);
}
